import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: LayoutProps<'/'>) {
  return (
    <html lang='en'>
      <body suppressHydrationWarning>
        <main className='relative h-screen'>{children}</main>
      </body>
    </html>
  )
}
