import type { Metadata } from 'next'
import * as fonts from '@/lib/fonts'
import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: LayoutProps<'/'>) {
  return (
    <html
      className={`${fonts.balsamiq.variable} ${fonts.montserrat.variable} ${fonts.neon.variable} ${fonts.saiba45.variable} antialiased`}
      dir='ltr'
      lang='es'
    >
      <body suppressHydrationWarning>
        <main className='relative h-screen'>{children}</main>
      </body>
    </html>
  )
}
